[package]
name = "alterware-launcher"
version = "0.2.3"
edition = "2021"
build = "res/build.rs"

[profile.release]
opt-level = "s"
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http_req = { version = "0.9.2", default-features = false, features = [
    "rust-tls",
] }
sha1_smol = "1.0.0"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
rand = "0.8.5"
semver = "1.0.18"

[target.'cfg(windows)'.dependencies]
steamlocate = "1.2.1"
mslnk = "0.1.8"

[build-dependencies]
winres = "0.1.12"

[package.metadata.winres]
OriginalFilename = "alterware-launcher.exe"
FileDescription = "AlterWare mod updater & launcher"
ProductName = "AlterWare Launcher"